### ISSUE TITLE
 Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by enpboss** [adafruit/node_mpr121#5]
While i try to run example.js, i facing this issue. 

Respberry PI - 3 Model B ... using specified raspberry pi TOUCH hat MPR121

```
/usr/lib/node_modules/adafruit-mpr121/node_modules/bindings/bindings.js:91
  throw err
  ^
Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/build/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/build/Debug/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/build/Release/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/out/Debug/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/Debug/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/out/Release/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/Release/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/build/default/i2c.node
 → /usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/compiled/6.11.0/linux/arm/i2c.node
    at bindings (/usr/lib/node_modules/adafruit-mpr121/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/adafruit-mpr121/node_modules/i2c-bus/i2c-bus.js:4:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/adafruit-mpr121/index.js:3:13)
```

**Comment by enpboss** [comment]
At last i found , Problem with Hardware version this lib is looking for BCM2708 or BCM 2709 but i updated latesr kernal it is BCM2835, so please update the module
